# -*- coding: utf-8 -*-
"""Copy of Untitled6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnx-1kK9ybtUttMY5h8owxVPJvW8cRh9
"""

pip install transformers
pip install scispacy
pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.1/en_core_sci_sm-0.5.1.tar.gz
pip install streamlit  # if you deploy locally

report = """
The CT scan shows a 2.3 cm hypodense lesion in the right hepatic lobe.
No evidence of metastatic spread. No lymphadenopathy.
"""
report = """
The CT scan shows a 2.3 cm hypodense lesion in the right hepatic lobe.
No evidence of metastatic spread. No lymphadenopathy.
"""

import scispacy
import spacy
nlp = spacy.load("en_core_sci_sm")

doc = nlp(report)
for entity in doc.ents:
    print(entity.text, "->", entity.label_)

from transformers import pipeline
nlp_pipeline = pipeline("ner", model="dslim/bert-base-NER")
results = nlp_pipeline(report)
for r in results:
    print(r)

from transformers import pipeline
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
summary = summarizer(report, max_length=60, min_length=20, do_sample=False)
print(summary[0]['summary_text'])

import streamlit as st

st.title("Medical Report Analyzer Bot")
user_input = st.text_area("Paste your medical report here:")

if st.button("Analyze"):
    doc = nlp(user_input)
    entities = [ent.text for ent in doc.ents]
    st.write("🔍 **Key Medical Terms Found:**")
    st.write(entities)